version: '3.8'

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb2
    volumes:
      - /mnt/influxdb/data:/var/lib/influxdb2:rw

    networks:
      compose-reload:
        aliases:
          - influxdb.local

    ports:
      - 8086:8086
    environment:
      - INFLUXDB_INIT_MODE=setup
      - INFLUXDB_INIT_USERNAME=vebproekt
      - INFLUXDB_INIT_PASSWORD=vebprogramiranje
      - INFLUXDB_INIT_BUCKET=proekt
      - INFLUXDB_INIT_ORG=FINKI
      - INFLUXDB_INIT_RETENTION=24h
      - INFLUXDB_INIT_ADMIN_TOKEN=YnsmXahQL4phIpK0MoA2dN3Yg2nhxx28QIKtp14cZLr-CB8WBAiYtKxaJvX8L0N7JvwbYWSxpN1K6oDbGLGurg==
    restart: unless-stopped
  python:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
        - ./:/app
    networks:
          - compose-reload
    depends_on:
      - influxdb
  app:
    build:
      context: .
      dockerfile: SpringDockerfile
    ports:
      - "8080:8080"
    environment:
      - INFLUXDB_URL=http://influxdb.local:8086
      - INFLUXDB_USERNAME=vebproekt
      - INFLUXDB_PASSWORD=vebprogramiranje
      - INFLUXDB_INIT_ORG=FINKI
      - INFLUXDB_DATABASE=proekt
      - INFLUXDB_INIT_ADMIN_TOKEN=YnsmXahQL4phIpK0MoA2dN3Yg2nhxx28QIKtp14cZLr-CB8WBAiYtKxaJvX8L0N7JvwbYWSxpN1K6oDbGLGurg==
    depends_on:
      - influxdb
    networks:
      - compose-reload


networks:
  compose-reload:
    driver: bridge