spring.application.name=Personalized-system-for-monitoring-vital-parameters
influxdb.url=http://localhost:8086/
influxdb.token=-AquLqmeSga2Hs_iTZ4ycMeoQYEHJ8pppejS9OYRTf_Z3f3B2iGBhJXIoCpL_kxtT77av0saeWdY4bM4oF8VGw==
influxdb.org=FINKI
influxdb.bucket=proekt
